=== Nushooz/Public/Old Code/Theory of Programming Languages/XML/SchemaValidation/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="Person">
		<xsd:complexType>
			<xsd:sequence>
			   <xsd:element name="name" type="NameType"/>
               <xsd:element name="degree">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                           <xsd:minLength value='2'/>
                           <xsd:maxLength value='2'/>
                        </xsd:restriction>
                    </xsd:simpleType>
               </xsd:element>
               <xsd:element name="class">
                   <xsd:simpleType>
                       <xsd:restriction base="xsd:string">
                          <xsd:minLength value='2'/>
                          <xsd:maxLength value='2'/>
                          <xsd:enumeration value="FR"/>
                          <xsd:enumeration value="SO"/>
                          <xsd:enumeration value="JR"/>
                          <xsd:enumeration value="SR"/>
                          <xsd:enumeration value="GR"/>
                       </xsd:restriction>
                   </xsd:simpleType>
               </xsd:element>    
               <xsd:element name="phone">
                   <xsd:simpleType>
                       <xsd:restriction base="xsd:string">
                          <xsd:minLength value='10'/>
                          <xsd:maxLength value='10'/>
                       </xsd:restriction>
                   </xsd:simpleType>
               </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="status" type="xsd:string"/>
            <xsd:attribute name="lastatt" type="xsd:string"/>
		</xsd:complexType>
    </xsd:element>
    <xsd:complexType name="NameType">
		<xsd:sequence>
		     <xsd:element name="last" type="xsd:string"/>
             <xsd:element name="middle" type="xsd:string"/>
		     <xsd:element name="first" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="lang" type="xsd:string"/>
	</xsd:complexType>
</xsd:schema>

=== Nushooz/Public/Old Code/Theory of Programming Languages/XML/SchemaValidation/person2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="person.xsd" status="Enrolled">
	<name lang="EN">
		<last>Blalock</last>
        <middle>Cody</middle>
		<first>Brandon</first>
	</name>
    <degree>BA</degree>
    <class>FR</class>
    <phone>6158981236</phone>
</Person>

=== Nushooz/Public/Old Code/Theory of Programming Languages/XML/SchemaValidation/person1.xml
<?xml version="1.0" encoding="UTF-8"?>

<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="person.xsd" status="Dropped" lastatt="2003-06-15">
	<name lang="EN">
		<last>Absher</last>
        <middle>Ray</middle>
		<first>James</first>
	</name>
    <degree>MC</degree>
    <class>JR</class>
    <phone>6158981234</phone>
</Person>

=== Nushooz/Public/Old Code/Theory of Programming Languages/XML/SchemaValidation/person3.xml
<?xml version="1.0" encoding="UTF-8"?>

<Person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="person.xsd" status="Withdrawn" lastatt="2003-06-20">
	<name lang="EN">
		<last>Bray</last>
        <middle>H</middle>
		<first>Thomas</first>
	</name>
    <degree>LA</degree>
    <class>JR</class>
    <phone>9318981235</phone>
</Person>
